version: '3.1'

services:
    db:
        image: mysql:8.0.26
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
            - MYSQL_DATABASE=wordpress
        command: '--default-authentication-plugin=mysql_native_password'
        networks:
            - app-network

    wordpress:
        depends_on:
            - db
        image: wordpress:5.8.0-apache
        container_name: wordpress
        restart: unless-stopped
        env_file: .env
        environment:
            - WORDPRESS_DB_HOST=db:3306
            - WORDPRESS_DB_USER=$MYSQL_USER
            - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
            - WORDPRESS_DB_NAME=wordpress
        volumes:
            - wordpress:/var/www/html
        networks:
            - app-network      

    webserver:
        depends_on:
            - wordpress
        image: jptosso/coraza-waf:latest
        container_name: webserver
        restart: unless-stopped
        environment:
            - CRS_VERSION=3.3.2
            - CRS_SETUP=true
            - CRS_EXCLUDE_WORDPRESS=true
        ports:
            - "80:80"
        volumes:
            - ./Caddyfile:/coraza/Caddyfile
        networks:
            - app-network            

volumes:
    wordpress:

networks:
    app-network:
        driver: bridge